### ISSUE TITLE
Create Mock Portal Database

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#10]
In for this story to be complete, the following criteria must be complete

-A PostgreSQL database that mimics Portals schema must be created
-The database must be hosted somewhere
-Others should be able to connect to it
-The sample data should be loaded into the mock

**Comment by sawyerwatts** [comment]
I took care of loading the sample data in #2 .

**Comment by Durecka** [comment]
@sawyerwatts Could you confirm what, if anything, is left that I should complete?

**Comment by sawyerwatts** [comment]
Really just go checkout out my PR.
