### ISSUE TITLE
Picking Up new Data from Portal

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#15]
In order for this story to be considered complete, the following criteria must be met,

-A system must be created that can pick up new data automatically from Portal or on a timer
-The system must be able to be run manually
-The system must not pick up duplicate data that has already been proceeded

**Comment by Durecka** [comment]
Arranging a meeting that will answer questions regarding this issue.

**Comment by Durecka** [comment]
Present understanding is that we need a persistent previous run state, containing the row_id, service date, service period, and year of the previous line processed.
For scheduled running, we wish to use a cron job, I assume.
For manual running, we need a command line entry point and interface.

Please confirm if anything here is incorrect or warrants further discussion.
