### ISSUE TITLE
Create notification system

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#16]
In order for this story to be considered complete, the following criteria must be met,

-A class must be made that is capable of sending out notifications
-The notifications must include at least email
-The notifications must be written to a file that the Django app can pick up(this may change depending on how the user wants the notifications to be posted)

**Comment by sawyerwatts** [comment]
A cool stretch goal for this issue's emailing functionality would be to allow for the user_email to be a list, and email each of them.
