### ISSUE TITLE
Set up testing framework

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#19]
In order for this story to be considered complete, the following criteria must be met,

-PyTest should be set up within the project
-A file structure for test should be created
-A example unit test should be created
-The example unit test should be able to run from command line
-Documentation is created on how to create new unit test and run them

**Comment by NelsonG6** [comment]
pytest runs, documentation collected

**Comment by tinlun** [comment]
Which commit closed this issue?
