### ISSUE TITLE
Create Aperture Docker Container

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#22]
In order for this story to be considered complete the following must be completed

-Aperture should be inside a docker container
-Spinning up the containers brings up a container of Aperture
-A script should be created to be able to rebuild Aperture
-A script should be created that can spin up and shut down Aperture
-Basic documentation on how to spin up,shut down, and access Aperture should be created

**Comment by Erik-Hanson** [comment]
For the two points,
"A script should be created to be able to rebuild Aperture"
and
"A script should be created that can spin up and shut down Aperture"
is this referring to the Aperture docker container or the database?

**Comment by Erik-Hanson** [comment]
Folder containing scripts to do all of the required stuff here can be found [here](https://drive.google.com/open?id=1pe8A-ZxamWSJwfpMotNFh3ottuumpeeR). For documentation on how to use these scripts go [here](https://docs.google.com/document/d/1zPbw797tWJ9rspvuydkAPRWI9Gco-vkqp69Vs73JycA/edit?usp=sharing)
