### ISSUE TITLE
Research pipeline dockerization

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#26]
In order for this story to be considered complete, the following criteria should be met,

-Instructions/a plan for how to dockerize the pipeline should be made

**Comment by NelsonG6** [comment]
https://docs.google.com/document/d/1e_jQqrJIfQaJpSCt-67J_YpMzKaZ06hoGX4Uu9ZeZBY/edit?usp=sharing Preliminary document with details on adding a python script and running it

**Comment by NelsonG6** [comment]
Issue finished for this sprint, grabbing issue for next sprint as well
