### ISSUE TITLE
Create unit test for database opertions

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#27]
In order for this story to be considered complete the following must be completed

-Database must be mocked out
-Unit tests for testing database opertions must be completed
-Unit tests should have a 95%+ coverage rate of database opertions

**Comment by sawyerwatts** [comment]
I'm tired of these sitting in my browser until the sprint arrives, so I'm pasting some possibly helpful links here. 

- https://docs.pytest.org/en/latest/reference.html#std:fixture-monkeypatch
- https://docs.pytest.org/en/latest/monkeypatch.html
- https://www.patricksoftwareblog.com/monkeypatching-with-pytest/
- https://stackoverflow.com/questions/33554815/pytest-fixture-params-with-monkeypatch
- https://joshpeak.net/posts/2019-06-18-Advanced-python-testing.html#mocks-spies-stubs-and-monkey-patches
