### ISSUE TITLE
Allow loading from portal/mock database

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#3]
In order for this story to be accepted the following criteria should be true,

-A python script was created/amended to allow data from portal/mock database to be loaded onto Aperture
-The script should do basic data verification(i.e checks for nulls) and flag them using the system we discussed
-System should be able to have its connection string swapped out very to allow for switching from dummy database to Portal

**Comment by sawyerwatts** [comment]
Whoever picks this up, please check in with me.

**Comment by sawyerwatts** [comment]
I have a working general ctran table read/write on database_operations.

**Comment by sawyerwatts** [comment]
I'll also take care of reading the whole tables as well. So this issue could focus on updating them and reading specific parts, like the data that would be unprocessed.

**Comment by sawyerwatts** [comment]
Basic data verification is part of flaggers and will not be done here.

**Comment by Durecka** [comment]
For this issue, I have worked to provide a command line interface via arguments for running the pipeline over a range of dates (supplied via args at this time pending further information on the interaction between Docker and pipeline initiation). The query to select the range of dates was also created. The code stops at the point the pipeline would begin to run, as that is outside the scope of this issue.
Relevant modules:
- Logger used for error printing of argument parsing on input date parameters
- Test framework to test querying Aperture/Portal
- Environment variables already in use to establish database credentials
