### ISSUE TITLE
Finish Pipeline

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#30]
This story may already be mostly complete, this story is to verify it. In order for this story to be complete the following must be true.

-The pipeline takes in a SQL query from portal for fresh data
-The pipeline must immediately act on this query and get the fresh data
-The pipeline must automatically analyze and flag the data, storing the flags in the database

**Comment by Durecka** [comment]
I handled creating the query to select a service date's data, as there was some overlap with Issue #3 . Date range selection is performed via command line arguments, which will likely be revised when we have a better understanding of how Docker will interact with pipeline initiation.

**Comment by sawyerwatts** [comment]
Regarding the third point, #51 could probably taken care of here as well, if you want.

**Comment by NelsonG6** [comment]
its done
