### ISSUE TITLE
Add more in depths flags

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#37]
In order for this story to be considered complete the following must be completed

- New flags must be created and added to the repo that covers more extensive likely use cases(i.e too far from a stop or going too fast/slow)
-New flags must be added to existing documentation
-New flags analyzers must be added to the current default analyzer

**Comment by gmillia** [comment]
3 new flaggers have been added (duplicate, unobserved stop, and unopened door).
