### ISSUE TITLE
Make check pointing system in preparation for cron job

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#50]
In order for this story to be complete there should be a system which remembers the last range of dates that were inputted into the pipeline. The system can also be called to enter all the data from the last date it ran to the current date.  The last date should be saved in a text file and have a method that can be called to save a new day for a checkpoint, and a method that can be called to get the last day processed.

**Comment by NelsonG6** [comment]
closing
