### ISSUE TITLE
Create Cron Job

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#52]
In order for this story to be considered complete there should be a Cron Job script created. This job will be responsible for running the pipeline every 24 hours and should have a way to modify the amount of time between jobs. Wether that is editing a file, stopping the pipeline and starting it again with a flag or something else. Cron job should use checkpointing system to get last date used and go from there.

**Comment by sawyerwatts** [comment]
This involves spinning the docker instance up and feeding it query dates.
