### ISSUE TITLE
Slap some glue in them joints

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#66]
Glue the following components together,
Checkpointing,
Check all print and log statements use the logger
Argument interface

**Comment by sawyerwatts** [comment]
I would argue that print statements made during the CLI menu wouldn't have to be logged since the user is interacting with the application and does not need to check a log.

**Comment by sawyerwatts** [comment]
Table also has instances of using print when IOs._print would be more appropriate.

**Comment by sawyerwatts** [comment]
Checkpointing is already integrated during #71 .
