### ISSUE TITLE
Research dockerizeing Aperture

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#7]
In order for this story to be considered complete the following criteria should be met,

-Instructions/a plan for how to dockerize aperture should be made
-Documentation on dockerization should be made

**Comment by Erik-Hanson** [comment]
I believe that [this document](https://docs.google.com/document/d/14ShfT9-1mAbsYWSF8UBKBV-weqLJQxEvx_aBoSN_STU/edit?usp=sharing) should give us enough information on how to dockerize aperture. Any feedback on additional information in the document would be good if there is any.

**Comment by sawyerwatts** [comment]
I can't execute this right now but it looks good to me. I appreciate how you have included how to pass environment variables to the container, I was curious about that.
