### ISSUE TITLE
Create table to store data processed and have checkpointing use that

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#71]
In order for this story to be considered complete the following must be completed,
a new table must be created in the HIVE schema that stores the previously processed days.
The checkpointing system must be changed to use this database instead of the current txt file

**Comment by sawyerwatts** [comment]
The new table has been added to the schema in reqs and the Pipeline now has a Table subclass for it, as well as having methods to add and delete days.
