### ISSUE TITLE
Create a configuration system

### ISSUE THREAD

**Issue by wolakdav** [wolakdav/TeamBeeCapstoneProject#9]
In order for this story to be considered complete, the following criteria must be met,

-A file is created with default values for what is considered out of bounds for table column values
-The file also holds a email address for the notifcation system
-A static python class is created that loads the data and holds onto it
-All areas where these values were previously hardcoded should be replaced with a call to the python class
-The class should be able to be triggered manually from the command line to update its values from a file
-The class should be able to have its values updated from the command line
-Documentation should be created that explain how to change the values and where they are

**Comment by sawyerwatts** [comment]
I recall the sponsor stated wanted being able to load the info via environment variables, so I added `bin/env_data.sh` with documentation in #34 which sets username, password, db name, and hostname.

**Comment by tinlun** [comment]
"-The class should be able to have its values updated from the command line."
I need clarification on this requirement. Should the config file be updated from the command line?
